# Generated by Django 3.1.3 on 2023-05-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='lesson',
        ),
        migrations.AddField(
            model_name='choice',
            name='textcontent',
            field=models.CharField(default='Content', max_length=30),
        ),
    ]
