# Generated by Django 3.1.3 on 2023-05-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20230507_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='textcontent',
            field=models.TextField(),
        ),
    ]
