# Generated by Django 3.1.3 on 2023-05-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0006_auto_20230507_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='texcontent',
            new_name='contenido',
        ),
    ]
